### ISSUE TITLE
[REQ] add a (GH-compliant) license file

### ISSUE THREAD

**Issue by MarcoRavich** [chvolow24/jackdaw#1]
Hi there, 1st of all thanks for your interesting work !

Since we've "doxed" it in our [HyMPS project](https://github.com/forart/HyMPS#readme) (under the [AUDIO](https://github.com/forart/HyMPS#-) \ [DAWs page](https://github.com/forart/HyMPS/blob/main/DAWs.md#---) \ [Generic subsection](https://github.com/forart/HyMPS/blob/main/DAWs.md#generic-)), can you please add a "GH-compliant" license file ?

Expliciting licensing terms is extremely important to let other devs (and not only) understand how to reuse/adapt/modify your code in other open projects and vice-versa.

Although it may sounds like a minor aspect, license file omission obviously causes an inconsistent generation of the relative badge too:

![](https://flat.badgen.net/github/license/chvolow24/jackdaw/?label=LICENSE)
(badge-generator URL: https://flat.badgen.net/github/license/chvolow24/jackdaw/?label=LICENSE)

Anyway you can easily choose a "correct" one through the GH's license wizard tool.

Last but not least, let us know how we could improve - in your opinion - categorization/sorting of collected projects in order to push their evolution by favouring collaborations between developers (and not only).

Thanks in advance.

**Comment by chvolow24** [comment]
Hello, I've added what I believe should be a "github compliant" license file (MIT license). The badge still shows "no license," so please let me know if any other changes are needed!

**Comment by MarcoRavich** [comment]
Hi there, thanks for the add.

As you can see badge works now (the generator needs some time to sync).

Thanks again !
